### ISSUE TITLE
Add example that demonstrates save/load between program being closed and then reopened

### ISSUE THREAD

**Issue by Cassumbra** [hankjordan/bevy_save#11]
This would be helpful to see in action as it is a very common usecase and I don't think any of the examples here do so.

**Comment by hankjordan** [comment]
All of the examples allow you to create a save, close the game, re-open the game, and then load the save you had made previously. If you are having trouble reproducing this behavior then you have encountered a bug.

Note that as of `0.8` the examples are the "best case scenario" where entity IDs don't clash.

It is possible to do this in a real game but in all likelyhood you will need to use the other tools exposed by the crate eg `Builder` and `Snapshot` manually to achieve the results you want. While that isn't ideal, it still affords you significantly more flexibility than what you get out of the box.

My end goal is to make it so that you can use the simple `World::save()` and `World::load()` interface while also having the ability to deal with entity mapping / handle mapping / asset mapping / etc transparently. Unfortunately I have not found a way to make that work yet - of course suggestions are welcome.

**Comment by hankjordan** [comment]
> i tried reloading in breakout but i got a crash
> ```
> thread 'Compute Task Pool (3)' panicked at 'called `Result::unwrap()` on an `Err` value: MultipleEntities("bevy_ecs::query::state::QueryState<&mut bevy_transform::components::transform::Transform, bevy_ecs::query::filter::With<breakout::Paddle>>")', examples\breakout.rs:383:38
> ```

This issue was introduced by startup systems being automatically reordered in Bevy `0.10.1`.

The order of startup systems affects what Entity IDs are being given out.

With the default configuration of `bevy_save`, this matters and if there is a mismatch there can be duplicate entities.

In this case, it caused a crash.

Related: #10 

Closed as completed via [#016c36](https://github.com/hankjordan/bevy_save/commit/016c365f449f2e0c23762c3bdf8f5822a0de57d3).
